### ISSUE TITLE
errors in code

### ISSUE THREAD

**Issue by Thanos-DB** [matprst/PIA-on-CNN#3]
Hi Mathias,

thank you for open-sourcing your work, it is an interesting paper!
I am trying to run your code and i have found a few errors that do not let it run. There are some minor issues like mismatching parentheses or missing imports but there are other issues too. I was wondering if there is a different version that you could push.

Thank you,
Thanos

**Comment by matprst** [comment]
Hi Thanos,

Thank you for letting me know about the issues. I'm not sure what went wrong, but I've pushed a new version which should work now. I also added a README section about how to download CelebA and how the data directory should be organized.

Please let me know if there are any other issues.

**Comment by Thanos-DB** [comment]
Hi Mathias,

thank you for the quick response!
I ll let you know if i see anything else.
